### ISSUE TITLE
all request pass whitout code authorization

### ISSUE THREAD

**Issue by Iraecio** [zfcampus/zf-mvc-auth#123]
i make update day 22/07/2016 and all request is allowed whitout authorization :/

and all is config for oauth2 authorization ://

**Comment by webimpress** [comment]
@Iraecio probably because bug in v1.4.0 reported in #117 and fixed in #120 

Can you check please your code with changes from #120?

**Comment by Iraecio** [comment]
@webimpress 
yes with #120 fix problem of check header authorization 

thx
