### ISSUE TITLE
DefaultAuthenticationListenerFactory creates own instance of OAuth2Server

### ISSUE THREAD

**Issue by adamlundrigan** [zfcampus/zf-mvc-auth#45]
I'm attempting to integrate [Satellizer](https://github.com/sahat/satellizer) with Apigility.  Satellizer uses JWT Bearer, which [requires some extra setup on the Apigility side](https://gist.github.com/adamlundrigan/336e28e14cee2eb16dfb) (in bshaffer/oauth2-server-php, technically).  zf-mvc-auth's DefaultAuthenticationListenerFactory pulls all the pieces from zf-oauth2's configuration and builds a new OAuth2Server instance rather than pulling the pre-configured one that zf-oauth2 slaved long and hard to construct.  Would it be acceptable to modify the factory to pull the preconfigured instance?  (If yes, I can provide a PR)

Source: https://github.com/zfcampus/zf-mvc-auth/blob/master/src/Factory/DefaultAuthenticationListenerFactory.php#L75

**Comment by solcre** [comment]
Any updates on this ? We are planning to integrate Satellizer with Apigility as well
