### ISSUE TITLE
Per-API authentication

### ISSUE THREAD

**Issue by weierophinney** [zfcampus/zf-mvc-auth#55]
A feature we want to implement for 1.1.0 is the ability to specify authentication per-API. The rationale is that a number of developers would like to serve multiple APIs from the same application, but use different authentication based on the API (for instance, they may want LDAP-based authentication for an "internal" API, and OAuth2 for an external API, but both would run from the same Apigility application).

We also need to remain compatible with pre-1.1.0!

Currently, in the 1.0 series, authentication is an application-level concern. As such, we trigger it *before* routing happens. Changing to per-API will require:

- Moving authentication to occur post-routing (i.e., negative priority on the "route" event, but still prior to authorization).
- Checking first for a API-specific authentication. If found, that gets used, and we go no further.
- Checking next for application-wide authentication. If found, that gets used.

The hard part will be the "per-API" check, as it will have to be conventions-based; i.e., it will need to look at the namespace of the matched controller and compare it against known namespaces.

All authentication types *will* still be created at the application level, but *mapped* at the API level. This means we'll still have the top-level authentication key inside the `zf-mvc-auth` configuration, but will then *also* have a map of API module names => named authentication type.

**Comment by weierophinney** [comment]
One interesting note: we currently only define **two** types of authentication, "http" and "oauth2". "http" encompasses *both* basic and digest. We may need to change this to allow defining each of basic, digest or oauth2.

Ping @ezimuel — thoughts?

**Comment by EMCP** [comment]
I'm guessing OAuth1 is not in the cards, on the server side?

**Comment by TomHAnderson** [comment]
@EMCP there is not a zf-oauth1 library and I'll go on to opinion we shouldn't promote such old technology in zfcampus.

**Comment by EMCP** [comment]
I feel such old technology has advantages over OAuth2, but I hear your opinion.

**Comment by weierophinney** [comment]
#59 was created to address this.

**Comment by weierophinney** [comment]
@EMCP There are good and bad things about OAuth v1.x; the request signing was great, but it was also incredibly brittle for implementors. All that said: because authentication is an event, you can implement it and drop it in to listen at priority > 1; so long as your listener returns one of either the GuestIdentity or AuthenticatedIdentity, the default options will be omitted. However, it means you cannot configure it in the admin UI, nor, as the state of #59 currently stands, opt-in to per-API authentication types. I'll take that latter into consideration as we test the patch, as I think it could be useful to specify custom types, even if we don't handle them in the default listener.

**Comment by weierophinney** [comment]
Addressed in #59 — including custom types and adapters, @EMCP!
