### ISSUE TITLE
401 and 403 responses

### ISSUE THREAD

**Issue by stefanotorresi** [zfcampus/zf-mvc-auth#58]
In #apigility a user has recently posted this article:
http://robertlathanh.com/2012/06/http-status-codes-401-unauthorized-and-403-forbidden-for-authentication-and-authorization-and-oauth/

Now, as far as I can tell the approach of the module should reflect exactly the same interpretation, but I think there is problem in `ZF\MvcAuth\Authentication\DefaultAuthenticationPostListener`, as it returns too early and it is superseded by `ZF\MvcAuth\Authorization\DefaultAuthorizationPostListener`, so unauthenticated requests ends up in an empty 403 response rather than a 401.

If I got it right, the authentication listener basically just listens for authentication attempts, but it doesn't determine whether a specific request should be authenticated in the first place. Am I right?

One possible solution is to add further logic in the authorization listener, to determine if the request has to be authenticated and to to return a 401 in case no authentication is present, before even proceeding to check the ACL.

Toughts?

**Comment by webaaz** [comment]
I have the same vision, so I added my own AuthenticationListener attached to MvcAuthEvent::EVENT_AUTHENTICATION_POST with a weight of 50.
If I have no identity, I return a 401 API problem.

**Comment by weierophinney** [comment]
This is fixed as of #83
