### ISSUE TITLE
Multiple authentication adapters BC break

### ISSUE THREAD

**Issue by stefanotorresi** [zfcampus/zf-mvc-auth#65]
Before 1.1 it was possible to configure both http and oauth2 authentication adapters globally, as `DefaultAuthenticationListener` inferred the type to use from the request.

With 1.1, not only it's not possible anymore (because it's deemed as an "ambiguous case"), but it's neither possible to assign one custom adapter for every resource, nor multiple adapters for one resource.

Is the only solution to write my custom adapter and manually assign it to *every* resource? Couldn't we move [this block](https://github.com/zfcampus/zf-mvc-auth/blob/master/src/Authentication/DefaultAuthenticationListener.php#L166-L173) down and use the request before the map?

**Comment by weierophinney** [comment]
Can you provide an example of the configuration you were using previously?

**Comment by stefanotorresi** [comment]
here is an example:

```php
    'zf-mvc-auth' => [
        'authentication' => [
            'http' => [
                'accept_schemes' => [
                    'basic',
                ],
                'realm' => 'foobar',
            ],
        ],
    ],
    'zf-oauth2' => [
        'storage' => 'some-oauth2-storage-adapter',
    ],

this would end up in skipping the authentication, while the old listener was perfectly capable of using either of the methods based on the request headers.

**Comment by weierophinney** [comment]
I think the only way to accomplish it will be via a composite adapter; I'll work up a gist on one later, and we can potentially add it to zf-mvc-auth for an upcoming release.

**Comment by weierophinney** [comment]
@stefanotorresi As noted in IRC, I've gisted a potential approach here for the composite adapter: https://gist.github.com/weierophinney/fce00a22f779f1ce4ae7.

Probably an even better approach would be to create an AbstractFactory for handling the various adapters. Names would be prefixed with something like "zf-mvc-auth-adapter-{type}", and the "{type}" would be used as the key to pull from `zf-mvc-auth.authentication.adapters` when creating the adapter. This would prevent the duplicate adapter situation, and make it possible to pull the adapter from the SM directly. It would also mean that the delegator factory I propose in the gist would be unnecessary, as it would be able to potentially pull the composite adapter from the SM directly by service name, so long as it has an entry in the adapters configuration.

**Comment by stefanotorresi** [comment]
perfect, I'll get at it ASAP!

**Comment by weierophinney** [comment]
@stefanotorresi Also, zfcampus/zf-oauth2#93 and zfcampus/zf-mvc-auth#67 *might* address your use case of having a global, fallback adapter, and API-specific overrides.
