### ISSUE TITLE
Migration from 1.0 to 1.1 but no ['zf-mvc-auth']['authentication']['map'] config

### ISSUE THREAD

**Issue by webaaz** [zfcampus/zf-mvc-auth#66]
I have updated my composer to migrate from 1.0 to 1.1.
But the ['zf-mvc-auth']['authentication']['map'] wasn't created automatically as defined in the readme.

**Note for users migrating from 1.0**: In the 1.0 series, authentication was
*per-application*, not per API. The migration to 1.1 should be seamless; if you
do not edit your authentication settings, or provide authentication information
to any APIs, your API will continue to act as it did. The first time you perform
one of these actions, the Admin API will create a map, mapping each version of
each service to the configured authentication scheme, and thus ensuring that
your API continues to work as previously configured, while giving you the
flexibility to define authentication per-API and per-version in the future.

So sorry, no more details about this bug.

**Comment by weierophinney** [comment]
@webaaz Did you run the admin UI? The migration tools only kick in on the first time you invoke the UI. Until then, the old configuration will be in play, *and should still work*. 

- Does your old configuration work?
- Have you run the admin UI since? If so, was the map created or not?

**Comment by webaaz** [comment]
I don't remember... Finally, I create the map manually

**Comment by weierophinney** [comment]
I'm leaving this open for a bit; I'm going to test the migration process later today to see if I see any similar issues. Thanks for getting back to me, @webaaz .

**Comment by weierophinney** [comment]
@webaaz Okay, confirmed; I've taken a 1.0.5 app to 1.1.0, and the migration is not happening on first load of the UI. Will address it today.

**Comment by weierophinney** [comment]
@webaaz It *does* work! But I was wrong about *when* it works. The migration happens the first time you access the *authentication* screen of the UI; essentially, it's not until you decide to inspect, edit, or otherwise change authentication that the migration occurs.

I've also verified that the OAuth2 workflow continues to work when after the migration occurs.
