### ISSUE TITLE
there si no way to add extra configurations to oauth server (custom grant_types)

### ISSUE THREAD

**Issue by cape** [zfcampus/zf-mvc-auth#70]
I need to add a custom grant type to the instances of oauth2server used in zf-mvc-auth.
There is no way to do this because there is no shared registry for all the oauth2 servers.
The class ZF\MvcAuth\Factory\DefaultAuthenticationListenerFactory creates a new oauth server every time that is called. 
Also,  ZF\OAuth2\Factory\OAuth2ServerFactory creates a new instance every time that is called. 

This could be fixed if zf-mvc-auth provides a way to add custom grants by configuration.

**Comment by TarasHots** [comment]
Not sure what do you mean by 'custom grant_types'. Do you mean really custom grant type implemented from scratch or just custom storage for one of the already existing? For the latter, you can simply set 'grand_types' property in your oauth config in autoload folder, and set grand types which you needs:

`'grant_types' => array(`
           ` 'client_credentials' => true,`
           ` 'authorization_code' => true,`
           ` 'password'           => true,`
           ` 'refresh_token'      => true,`
           ` 'jwt'                => true,`
       ` )`

**Comment by cape** [comment]
I mean custom grant types implemented from scratch.
I am doing Google and Facebook login integration, I have a custom grant
type to manage the google hybrid type of login.
Once that the web client get a code from Google its sended to the oauth
server using a custom grant type key. Then the server validate this code
and get an access token from google.

I was looking the code to figure out how to achieve this. And can't find a
clean way. the grant_types configuration key maybe should accept custom
grant types factories or instances, what do you think?

**Comment by weierophinney** [comment]
@cape I'm working on a solution now; it will encompass changes on both zf-oauth2 and zf-mvc-auth. In each case, the factory returned by the `ZF\OAuth2\Service\OAuth2Server` service will cache `OAuth2\Server` instances, making it safe for you to do this:

```php
$factory = $services->get('ZF\OAuth2\Service\OAuth2Server');
$server = $factory(); // application-level zf-oauth2 server, OR
$server = $factory('named-oauth2'); // per-api server instance, as provided in zf-mvc-auth

$server->{call a method}(...);
```

That should likely resolve your issue. I'll update this issue with pull requests for you to track shortly.

**Comment by weierophinney** [comment]
@cape #71 and zfcampus/zf-oauth2#95 will address this. I've also described in #92 how you can create a delegator factory for automating injection of your custom grant types once those patches are merged (will be within the hour).

**Comment by cape** [comment]
Thanks!! This will help me a lot.
I will test this asap!!!

Thanks again
