### ISSUE TITLE
Scope verification is not correct

### ISSUE THREAD

**Issue by TarasHots** [zfcampus/zf-mvc-auth#75]
Found this issue on the latest 1.7.1 version, and zf-mvc-auth's latest of 1.1.3. Problem is in false approving access for authorized users but with smaller scope access. I have an ACL roles called e.g. 'test' and 'live'. I have some resource called A_Resource, and allowed 'live' users access to it. This issue allows 'test' users to be accessed to A_Resource. I debugged a bit and this strange behaviour starts at:

```php
public function authenticate(Request $request, Response $response, MvcAuthEvent $mvcAuthEvent)
    {
        $content       = $request->getContent();
        $oauth2request = new OAuth2Request(
            $_GET,
            $_POST,
            array(),
            $_COOKIE,
            $_FILES,
            $_SERVER,
            $content,
            $request->getHeaders()->toArray()
        );
        if (! $this->oauth2Server->verifyResourceRequest($oauth2request)) {//here
            return false;
        }
        $token    = $this->oauth2Server->getAccessTokenData($oauth2request);
        $identity = new Identity\AuthenticatedIdentity($token);
        $identity->setName($token['user_id']);
        return $identity;
    }
```
 the method's signature is 

```php
public function verifyResourceRequest(RequestInterface $request, ResponseInterface $response = null, $scope = null)
```
As a result, here: 

```php
public function verifyResourceRequest(RequestInterface $request, ResponseInterface $response, $scope = null)
    {
        $token = $this->getAccessTokenData($request, $response);
        // Check if we have token data
        if (is_null($token)) {
            return false;
        }
        /**
         * Check scope, if provided
         * If token doesn't have a scope, it's null/empty, or it's insufficient, then throw 403
         * @see http://tools.ietf.org/html/rfc6750#section-3.1
         */
        //problem in $scope
        if ($scope && (!isset($token["scope"]) || !$token["scope"] || !$this->scopeUtil->checkScope($scope, $token["scope"]))) {
            $response->setError(403, 'insufficient_scope', 'The request requires higher privileges than provided by the access token');
            $response->addHttpHeaders(array(
                'WWW-Authenticate' => sprintf('%s realm="%s", scope="%s", error="%s", error_description="%s"',
                    $this->tokenType->getTokenType(),
                    $this->config['www_realm'],
                    $scope,
                    $response->getParameter('error'),
                    $response->getParameter('error_description')
                )
            ));
            return false;
        }
        // allow retrieval of the token
        $this->token = $token;
        return (bool) $token;
    }
```

 we got problem with $scope variable, because it's isn't false, it is null, and this breaks the statement and not sending 403 error. The rest of checks in that if statement are fine. But seems that scope should be provided, and appropriate logic for default values also need to be implemented... Probably the problem is in authenticate method, passing role, all works great, but didn't find way to get requested scope there...

Looking forward for your response

**Comment by pCoLaSD** [comment]
We have the same Problem here. I would like to suggest to pull request a feature to accomplish the scope verification. This feature should provide a new `authentication` sub-key named `scopes`. With respect to the already implemented ACL based authorization, this configuration could have the following layout.

As an example:
``` php
'authentication' => array(
    'scopes' => array(
        'default' => 'read_default write_default',
        'Controller\Service\Name' => array(
            'actions' => array(
                'action' => array(
                    'default' => 'read_anything',
                    'GET' => 'get_anything',
                    'POST' => 'post_anything',
                    // etc.
                ),
            ),
            'collection' => array(
                'default' => 'read_anything',
                'GET' => 'get_anything',
                'POST' => 'post_anything',
                // etc.
            ),
            'entity' => array(
                'default' => 'read_anything',
                'GET' => 'get_anything',
                'POST' => 'post_anything',
                // etc.
            ),
        ),
    ),
)
```

Then the `authenticate` Method should locate the requested resource and related scope to call the `verifyResourceRequest` with the scope parameter filled in.

This should solve this problem. What do you think?

**Comment by weierophinney** [comment]
> we got problem with $scope variable, because it's isn't false, it is null

This is irrelevant; `null` evaluates as a falsy value in PHP, so the conditional evaluates the same as if a `false` were provided; in other words, the conditional is not executed in this case.

The only way it could be executed is if we provided scopes to the verification method. We do not currently have plans to do that, as it duplicates the authorization system already present in zf-mvc-auth, providing more than one authorization mechanism to learn (right now, you learn one authorization mechanism, and it applies regardless of the authentication mechanism used).

If you want to accomplish the above, you can create an alternative `ZF\MvcAuth\Authentication\OAuth2Adapter` extension for it; we do not plan to do so at this time.
