### ISSUE TITLE
Restricted Zend Framework versions

### ISSUE THREAD

**Issue by SvenRtbg** [zfcampus/zf-mvc-auth#86]
This commit https://github.com/zfcampus/zf-mvc-auth/commit/bd9f42f16094c0bcd4cebbd597a2a0a0131f8c2b restricts the available Zend framework versions to below 2.5 for no apparent reason (other than testing on Travis, I think).

Unfortunately this conflicts with the already installed components in my API.

Testing shouldn't restrict the allowed versions, have a look at how Symfony deals with it: They test both with newest dependencies as well as oldest: https://github.com/symfony/symfony/blob/2.8/.travis.yml

I'd suggest to run the tests with `composer update` prior to execution instead of `composer install`, as well as `composer update --prefer-lowest` for some PHP versions.

**Comment by weierophinney** [comment]
@SvenRtbg There's a *very* good reason: Apigility still supports PHP 5.3, but ZF 2.5 and up *does not*. This was the reason for the change.

We're determining today if we'll do the 1.2 release still with PHP 5.3 support, or drop it; if we do release with 5.3 support, we'll likely do an immediate subsequent 1.3 release that drops it. However, to keep the 5.3 support, the changes MUST be in place as detailed in the commit you reference.

**Comment by SvenRtbg** [comment]
Please give some details on where exactly the support for PHP 5.3 will affect the usage of Apigility if one (or more) of the sub components will allow using a Zend Framework version that is incompatible with PHP 5.3, but due to using Composer would never be installed on that platform.

There are four methods of how to install Apigility, and I consider this the most dangerous step which may leave new users in a dead end.
1. The Apigility install script - is completely under your control and is supposed to install the correct dependencies based on the PHP version being used. And I wouldn't mind if even on PHP 7 this would still install an older version of Zend framework initially.
2. Downloading a tar ball - also completely under your control.
3. Using `composer create-project` - the skeleton zfcampus/zf-apigility-skeleton references zendframework ~2.4 in version 1.1.1. Composer will only install the versions referenced in the `composer.lock` file, so this also gives full control (and I must mention that it will by default install Zend Framework 2.4.0 as we speak, missing the security patch in 2.4.1 - it seems that running ` composer update` as the last step is highly recommended to not use outdated or dangerous components).
4. `git clone` and `composer install` will do basically the same as composer create-project.

It is your responsibility to not deliver dependencies that are incompatible with PHP 5.3 in all these channels, or that may break installation, but I don't see why this should happen.

On the other hand, suddenly restricting the ZF2 version leaves me in an unpleasant situation: If I choose to use a ZF 2.5 component anywhere else, I will not be able to update to the most recent versions of these Apigility components. Or the other way round: If I choose to use the latest release of Apigility components, I cannot use ZF 2.5 or anything that uses this version, because it seems to be incompatible - this will also affect other packages that rely on ZF2 2.5, which cannot be installed.
