### ISSUE TITLE
Use my own PDO adapter

### ISSUE THREAD

**Issue by webaaz** [zfcampus/zf-mvc-auth#87]
Hi!

I use Oauth with Postgresql and I need to override ZF\OAuth2\Adapter\PdoAdapter with my own Adapter

My configuration is:
```
<?php
return array(
    'zf-oauth2' => array(
        'db' => array(
            'dsn_type' => 'PDO',
            'dsn' => 'pgsql:host=192.168.42.11;port=5432;dbname=****',
            'username' => '****',
            'password' => '****',
        ),
    ),

    'zf-mvc-auth' => array(
        'authentication' => array(
            'adapters' => array(
                'oauth2' => array(

                    'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',
                    'pdoadapter' => '',

                    'storage' => array(
                        'adapter' => 'pdo',
                        'storage' => 'Application\Service\OAuth2Adapter',
                        'dsn' => 'pgsql:host=192.168.42.11;port=5432;dbname=****',
                        'route' => '/oauth',
                        'username' => '****',
                        'password' => '****',

                        'storage_settings' => array(
                            'user_table' => 'organization.people'
                        ),
                    ),
                ),
            ),
        ),
    ),
);

```

ZF\MvcAuth\Factory\OAuth2ServerFactory ::createPdoAdapter return a new ZF\OAuth2\Adapter\PdoAdapter;

I can't use my override Application\Service\OAuth2Adapter

**Comment by webaaz** [comment]
It used to work when I defined the storage into the zf-oauth2 key. But there was other problems. @see https://groups.google.com/a/zend.com/forum/#!topic/apigility-users/tAk8bjhWJdY

**Comment by webaaz** [comment]
My last working configuration is explained here : https://groups.google.com/a/zend.com/forum/#!topic/apigility-users/O6rWJpzSzIA

**Comment by weierophinney** [comment]
@webaaz I'm looking now at the configuration file for the module, and there's an example in there that is relevant:

```php
return [
    'zf-mvc-auth' => [
        'authentication' => [
            'adapters' => [
                'custom-oauth2' => [ // specify a name for your adapter
                    'adapter' => 'ZF\MvcAuth\Authentication\OAuth2Adapter', // The style of authentication adapter
                    'storage' => [ // this key is required; it's the configuration to use when creating the OAuth2 storage adapter
                        'storage' => 'Some\Storage\Service\Name', // <- This is what you're looking for; this is a service name for a custom OAuth2\Server\Storage adapter
                        'route' => '/oauth', // <- this is required, but will vary based on adapter
                    ],
                ],
            ],
        ],
    ],
];
```

With the above example, you'll need to have a service registered in your configuration for `Some\Storage\Service\Name`. The factory will then pull that service to use as the storage adapter to inject into `OAuth2\Server`.

One note: if you do the above, do **not** include an "adapter" key at the same level:

```php
return [
    'zf-mvc-auth' => [
        'authentication' => [
            'adapters' => [
                'custom-oauth2' => [
                    'adapter' => 'ZF\MvcAuth\Authentication\OAuth2Adapter',
                    'storage' => [
                        'storage' => 'Some\Storage\Service\Name',
                        'route' => '/oauth',
                        'adapter' => 'pdo', // DO NOT INCLUDE THIS!!!
                    ],
                ],
            ],
        ],
    ],
];
```

If that key is present, the factory will try and create a default `PdoAdapter` instance with the specified configuration!

Give that a try, and report back as to whether or not that works for you.

**Comment by webaaz** [comment]
It's ok, I've missed the 'adapter' => 'pdo'
But finally the storage_settings/user_table must be defined in zf-oauth2 conf.
It doesn't work without the default pdo adapter.

**Comment by weierophinney** [comment]
@webaaz Where are you putting `storage_settings`? They should be under the `options` sub-key:

```php
return [
    'zf-mvc-auth' => [
        'authentication' => [
            'adapters' => [
                'custom-oauth2' => [
                    'adapter' => 'ZF\MvcAuth\Authentication\OAuth2Adapter',
                    'storage' => [
                        'storage' => 'Some\Storage\Service\Name',
                        'route' => '/oauth',
                        'options' => [
                            'storage_settings' => [
                                // PUT THEM HERE
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
```

**Comment by weierophinney** [comment]
@webaaz This might help you:

- http://akrabat.com/custom-oauth2-authentication-in-apiiglity/

**Comment by webaaz** [comment]
Thanks @weierophinney, it's exactly what I've done and it works perfectly!

**Comment by kilroy05** [comment]
resurrecting and old post, but http://akrabat.com/custom-oauth2-authentication-in-apiiglity/ doesn't work for me
probably doing something wrong :\

**Comment by weierophinney** [comment]
@kilroy05 A closed issue is not the place to ask questions! :smiley:

For questions, we have [our Slack](https://zendframework-slack.herokuapp.com) and [our forums](https://discourse.zendframework.com/).

**Comment by kilroy05** [comment]
Fair enough. I'll join you on slack
Thanks for the reply
