### ISSUE TITLE
Apigility - Authentication - Per Api authentication adapter - Authorization problem

### ISSUE THREAD

**Issue by nuxwin** [zfcampus/zf-mvc-auth#92]
Don't know if this is more related to this module so ;)

See https://github.com/zfcampus/zf-apigility-skeleton/issues/104:

- HTTP auth is updating the response instance with a 401 status when no credentials are passed, making it impossible to have public parts of an API that uses HTTP authentication.

**Comment by nuxwin** [comment]
@weierophinney 

I'll do a PR in few minutes for the referenced bug. Changes made will be done in the **ZF\MvcAuth\Authentication\HttpAdapter**.

Here I'll simply mimic the **OAuth* adapter behavior. E.g: *When no credential were present at all, we just return a guest identity*. Then, this solves the issue. The **ZF\Apigility\MvcAuth\UnauthenticatedListener** will simply return due to the absence of the authentication result and thus, the authorization process for guest identity will be performed as it should.

**BTW:** To be able to reproduce the issue referenced here, only one Basic auth adapter must be configured.

**Comment by PowerKiKi** [comment]
I fail to see how it solve the issue. IMHO, you have to know whether the request is for a private or public API in order to either return a 401 or a successful response. How can you differentiate between those two cases before routing (and thus authentication configuration) ?

**Comment by nuxwin** [comment]
@weierophinney 

My fix was wrong after all...  It prevent challenge of client when needed...

```php
...
'zf-mvc-auth' => [
	'authentication' => 

		'adapters' => [
			'http' => [
				// HTTP auth adapter configuration
			],
			'whatever' => [
				// Whatever auth adapter configuration
			],
		],

		'map' => [
			'API/VERSION1' => 'basic',
			'API/VERSION2 => 'whatevertype'
		]
	]
]
...
```
Now, let imagine the following scenario: A client request the following URI /host.tld/API/VERSION1 (here, the matching authentication type is `basic`). No `Authorization` header is sent by the client.

Then, the following will occurs in the default authentication listener:

- getTypeFromRequest() will not be called (we have already an authentication type which is `basic`)
- pre-flight auth tasks will not be called on auth adapter. In that case, this involve that the client will not - be challenged (no 401 status code, nor WWW-Authenticate header)
- authenticate() method on the MVC authentication adapter will be called (That adapter matches the 'basic' authentication type type)
	
At this point, if the mvc http adapter don't find the `Authorization` header, it will simply return a `GuestIdentity`. So, later on, the authorization listener will simply set a 403 status code if `GuestIdentity` is not allowed to access the resource.

I'll investigate and try to provide a patch.

So we have the following to fix:

Allow an API to provide both public and private resource by sending correct HTTP status and challenge client only when needed. I'll work on that this month.
